### PR TITLE
Fix secret sanitizing for non string values

### LINKED ISSUE #108: Secret scrubbing should maintain JSON schema
#107 introduced scrubbing of screts from state. It recurses into objects, but doesn't currently recurse into arrays, so misses some secrets.

Also, the scrubbed value is always a string. Where the original value was not a string (e.g. object or array) it will fail to unmarshal the value into the target types.

### PR DESCRIPTION
**Pull request by danielrbradley**
- Use callback instead of fixed value for secret replacement.
- Find all strings recursively in JSON objects for replacement.
- Handle difference between gRPC using "value" and state using a "plaintext" string.

Fixes #108

### CODE REVIEW

File: pulumitest/sanitize/sanitize.go [hunk 1]
```diff
@@ -51,44 +51,86 @@ func SanitizeSecretsInGrpcLog(log json.RawMessage) json.RawMessage {
...
+		r.Outputs = sanitizeSecretsInObject(r.Outputs, sanitizeStateSecret)
 		resources[i] = r
 	}
 }
 
-var stateSecretReplacement = map[string]any{
-	secretSignature: "1b47061264138c4ac30d75fd1eb44270",
-	"plaintext":     `"` + plaintextSub + `"`, // must be valid JSON, hence quoted
+func sanitizeStateSecret(secretObj map[string]any) map[string]any {
+	// State file secrets either have a plaintext field which is any serialized JSON value
```
Comment (thomas11) [inline pulumitest/sanitize/sanitize.go:77]: "either" or ...?

**Review by thomas11 — APPROVED** [review]
Workflow failure due to my recent change in #3651 but otherwise LGTM
